// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.17.0-bufbuild-protocompile-easyp
// source: tenant/v1/tenant.proto

// Package содержит API v1 для работы с сервисом BotBooker

package tenant_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статус арендатора
type TenantStatus int32

const (
	TenantStatus_TENANT_STATUS_UNSPECIFIED TenantStatus = 0
	TenantStatus_TENANT_STATUS_ACTIVE      TenantStatus = 1
	TenantStatus_TENANT_STATUS_SUSPENDED   TenantStatus = 2
	TenantStatus_TENANT_STATUS_DELETED     TenantStatus = 3
)

// Enum value maps for TenantStatus.
var (
	TenantStatus_name = map[int32]string{
		0: "TENANT_STATUS_UNSPECIFIED",
		1: "TENANT_STATUS_ACTIVE",
		2: "TENANT_STATUS_SUSPENDED",
		3: "TENANT_STATUS_DELETED",
	}
	TenantStatus_value = map[string]int32{
		"TENANT_STATUS_UNSPECIFIED": 0,
		"TENANT_STATUS_ACTIVE":      1,
		"TENANT_STATUS_SUSPENDED":   2,
		"TENANT_STATUS_DELETED":     3,
	}
)

func (x TenantStatus) Enum() *TenantStatus {
	p := new(TenantStatus)
	*p = x
	return p
}

func (x TenantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tenant_v1_tenant_proto_enumTypes[0].Descriptor()
}

func (TenantStatus) Type() protoreflect.EnumType {
	return &file_tenant_v1_tenant_proto_enumTypes[0]
}

func (x TenantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantStatus.Descriptor instead.
func (TenantStatus) EnumDescriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

// Основная сущность арендатора
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Status        TenantStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=tenant.v1.TenantStatus" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Произвольные параметры/настройки
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

func (x *Tenant) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Запрос на получение информации о тенанте по его UUID
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Запрос на создание нового тенанта
type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTenantRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ, содержащий данные тенанта
type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// Запрос списка тенантов с поддержкой пагинации
type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *ListTenantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Ответ со списком тенантов и токеном следующей страницы
type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Запрос на удаление тенанта по его UUID
type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_tenant_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTenantRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x16tenant/v1/tenant.proto\x12\ttenant.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x85\x03\n" +
	"\x06Tenant\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12\x1d\n" +
	"\x04slug\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04slug\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.tenant.v1.TenantStatusR\x06status\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.tenant.v1.Tenant.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x10GetTenantRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\"\xda\x01\n" +
	"\x13CreateTenantRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12\x1d\n" +
	"\x04slug\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04slug\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.tenant.v1.CreateTenantRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x0eTenantResponse\x12)\n" +
	"\x06tenant\x18\x01 \x01(\v2\x11.tenant.v1.TenantR\x06tenant\"Y\n" +
	"\x12ListTenantsRequest\x12$\n" +
	"\tpage_size\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"j\n" +
	"\x13ListTenantsResponse\x12+\n" +
	"\atenants\x18\x01 \x03(\v2\x11.tenant.v1.TenantR\atenants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"3\n" +
	"\x13DeleteTenantRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid*\x7f\n" +
	"\fTenantStatus\x12\x1d\n" +
	"\x19TENANT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TENANT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17TENANT_STATUS_SUSPENDED\x10\x02\x12\x19\n" +
	"\x15TENANT_STATUS_DELETED\x10\x032\x9a\x03\n" +
	"\rTenantService\x12_\n" +
	"\tGetTenant\x12\x1b.tenant.v1.GetTenantRequest\x1a\x19.tenant.v1.TenantResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/tenants/{uuid}\x12a\n" +
	"\fCreateTenant\x12\x1e.tenant.v1.CreateTenantRequest\x1a\x19.tenant.v1.TenantResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tenants\x12a\n" +
	"\vListTenants\x12\x1d.tenant.v1.ListTenantsRequest\x1a\x1e.tenant.v1.ListTenantsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/tenants\x12b\n" +
	"\fDeleteTenant\x12\x1e.tenant.v1.DeleteTenantRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/tenants/{uuid}B<Z:github.com/botbooker/bb-core/pkg/proto/tenant/v1;tenant_v1b\x06proto3"

var (
	file_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_tenant_v1_tenant_proto_rawDescData []byte
)

func file_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_v1_tenant_proto_rawDesc), len(file_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_tenant_v1_tenant_proto_rawDescData
}

var file_tenant_v1_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tenant_v1_tenant_proto_goTypes = []any{
	(TenantStatus)(0),             // 0: tenant.v1.TenantStatus
	(*Tenant)(nil),                // 1: tenant.v1.Tenant
	(*GetTenantRequest)(nil),      // 2: tenant.v1.GetTenantRequest
	(*CreateTenantRequest)(nil),   // 3: tenant.v1.CreateTenantRequest
	(*TenantResponse)(nil),        // 4: tenant.v1.TenantResponse
	(*ListTenantsRequest)(nil),    // 5: tenant.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),   // 6: tenant.v1.ListTenantsResponse
	(*DeleteTenantRequest)(nil),   // 7: tenant.v1.DeleteTenantRequest
	nil,                           // 8: tenant.v1.Tenant.MetadataEntry
	nil,                           // 9: tenant.v1.CreateTenantRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_tenant_v1_tenant_proto_depIdxs = []int32{
	0,  // 0: tenant.v1.Tenant.status:type_name -> tenant.v1.TenantStatus
	8,  // 1: tenant.v1.Tenant.metadata:type_name -> tenant.v1.Tenant.MetadataEntry
	10, // 2: tenant.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: tenant.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: tenant.v1.CreateTenantRequest.metadata:type_name -> tenant.v1.CreateTenantRequest.MetadataEntry
	1,  // 5: tenant.v1.TenantResponse.tenant:type_name -> tenant.v1.Tenant
	1,  // 6: tenant.v1.ListTenantsResponse.tenants:type_name -> tenant.v1.Tenant
	2,  // 7: tenant.v1.TenantService.GetTenant:input_type -> tenant.v1.GetTenantRequest
	3,  // 8: tenant.v1.TenantService.CreateTenant:input_type -> tenant.v1.CreateTenantRequest
	5,  // 9: tenant.v1.TenantService.ListTenants:input_type -> tenant.v1.ListTenantsRequest
	7,  // 10: tenant.v1.TenantService.DeleteTenant:input_type -> tenant.v1.DeleteTenantRequest
	4,  // 11: tenant.v1.TenantService.GetTenant:output_type -> tenant.v1.TenantResponse
	4,  // 12: tenant.v1.TenantService.CreateTenant:output_type -> tenant.v1.TenantResponse
	6,  // 13: tenant.v1.TenantService.ListTenants:output_type -> tenant.v1.ListTenantsResponse
	11, // 14: tenant.v1.TenantService.DeleteTenant:output_type -> google.protobuf.Empty
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tenant_v1_tenant_proto_init() }
func file_tenant_v1_tenant_proto_init() {
	if File_tenant_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_v1_tenant_proto_rawDesc), len(file_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_v1_tenant_proto_depIdxs,
		EnumInfos:         file_tenant_v1_tenant_proto_enumTypes,
		MessageInfos:      file_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_tenant_v1_tenant_proto = out.File
	file_tenant_v1_tenant_proto_goTypes = nil
	file_tenant_v1_tenant_proto_depIdxs = nil
}
