// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	models "bookerbotapi/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockBookingRepository) CreateBooking(ctx context.Context, booking *models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingRepository)(nil).CreateBooking), ctx, booking)
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(ctx context.Context, id string) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, id)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), ctx, id)
}

// GetBookingsByServiceAndDate mocks base method.
func (m *MockBookingRepository) GetBookingsByServiceAndDate(ctx context.Context, serviceID string, date time.Time) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByServiceAndDate", ctx, serviceID, date)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByServiceAndDate indicates an expected call of GetBookingsByServiceAndDate.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByServiceAndDate(ctx, serviceID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByServiceAndDate", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByServiceAndDate), ctx, serviceID, date)
}

// GetBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetBookingsByUserID(ctx context.Context, userID, status string, limit, offset int) ([]models.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByUserID(ctx, userID, status, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByUserID), ctx, userID, status, limit, offset)
}

// UpdateBookingStatus mocks base method.
func (m *MockBookingRepository) UpdateBookingStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockBookingRepositoryMockRecorder) UpdateBookingStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBookingStatus), ctx, id, status)
}

// MockServiceRepository is a mock of ServiceRepository interface.
type MockServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRepositoryMockRecorder
}

// MockServiceRepositoryMockRecorder is the mock recorder for MockServiceRepository.
type MockServiceRepositoryMockRecorder struct {
	mock *MockServiceRepository
}

// NewMockServiceRepository creates a new mock instance.
func NewMockServiceRepository(ctrl *gomock.Controller) *MockServiceRepository {
	mock := &MockServiceRepository{ctrl: ctrl}
	mock.recorder = &MockServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRepository) EXPECT() *MockServiceRepositoryMockRecorder {
	return m.recorder
}

// CreateService mocks base method.
func (m *MockServiceRepository) CreateService(ctx context.Context, service *models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateService indicates an expected call of CreateService.
func (mr *MockServiceRepositoryMockRecorder) CreateService(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockServiceRepository)(nil).CreateService), ctx, service)
}

// DeleteService mocks base method.
func (m *MockServiceRepository) DeleteService(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteService", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockServiceRepositoryMockRecorder) DeleteService(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockServiceRepository)(nil).DeleteService), ctx, id)
}

// GetServiceByID mocks base method.
func (m *MockServiceRepository) GetServiceByID(ctx context.Context, id string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByID", ctx, id)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByID indicates an expected call of GetServiceByID.
func (mr *MockServiceRepositoryMockRecorder) GetServiceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByID", reflect.TypeOf((*MockServiceRepository)(nil).GetServiceByID), ctx, id)
}

// GetServicesByMerchantID mocks base method.
func (m *MockServiceRepository) GetServicesByMerchantID(ctx context.Context, merchantID string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByMerchantID indicates an expected call of GetServicesByMerchantID.
func (mr *MockServiceRepositoryMockRecorder) GetServicesByMerchantID(ctx, merchantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByMerchantID", reflect.TypeOf((*MockServiceRepository)(nil).GetServicesByMerchantID), ctx, merchantID)
}

// ListServicesFiltered mocks base method.
func (m *MockServiceRepository) ListServicesFiltered(ctx context.Context, merchantID, nameContains string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesFiltered", ctx, merchantID, nameContains)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesFiltered indicates an expected call of ListServicesFiltered.
func (mr *MockServiceRepositoryMockRecorder) ListServicesFiltered(ctx, merchantID, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesFiltered", reflect.TypeOf((*MockServiceRepository)(nil).ListServicesFiltered), ctx, merchantID, nameContains)
}

// MockStaffRepository is a mock of StaffRepository interface.
type MockStaffRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStaffRepositoryMockRecorder
}

// MockStaffRepositoryMockRecorder is the mock recorder for MockStaffRepository.
type MockStaffRepositoryMockRecorder struct {
	mock *MockStaffRepository
}

// NewMockStaffRepository creates a new mock instance.
func NewMockStaffRepository(ctrl *gomock.Controller) *MockStaffRepository {
	mock := &MockStaffRepository{ctrl: ctrl}
	mock.recorder = &MockStaffRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffRepository) EXPECT() *MockStaffRepositoryMockRecorder {
	return m.recorder
}

// CreateStaff mocks base method.
func (m *MockStaffRepository) CreateStaff(ctx context.Context, staff *models.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaff", ctx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStaff indicates an expected call of CreateStaff.
func (mr *MockStaffRepositoryMockRecorder) CreateStaff(ctx, staff interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaff", reflect.TypeOf((*MockStaffRepository)(nil).CreateStaff), ctx, staff)
}

// DeleteStaff mocks base method.
func (m *MockStaffRepository) DeleteStaff(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStaff", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStaff indicates an expected call of DeleteStaff.
func (mr *MockStaffRepositoryMockRecorder) DeleteStaff(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStaff", reflect.TypeOf((*MockStaffRepository)(nil).DeleteStaff), ctx, id)
}

// GetStaffByID mocks base method.
func (m *MockStaffRepository) GetStaffByID(ctx context.Context, id string) (*models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffByID", ctx, id)
	ret0, _ := ret[0].(*models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffByID indicates an expected call of GetStaffByID.
func (mr *MockStaffRepositoryMockRecorder) GetStaffByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffByID", reflect.TypeOf((*MockStaffRepository)(nil).GetStaffByID), ctx, id)
}

// GetStaffByMerchantID mocks base method.
func (m *MockStaffRepository) GetStaffByMerchantID(ctx context.Context, merchantID string) ([]models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffByMerchantID indicates an expected call of GetStaffByMerchantID.
func (mr *MockStaffRepositoryMockRecorder) GetStaffByMerchantID(ctx, merchantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffByMerchantID", reflect.TypeOf((*MockStaffRepository)(nil).GetStaffByMerchantID), ctx, merchantID)
}

// ListStaffFiltered mocks base method.
func (m *MockStaffRepository) ListStaffFiltered(ctx context.Context, merchantID, nameContains string) ([]models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStaffFiltered", ctx, merchantID, nameContains)
	ret0, _ := ret[0].([]models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStaffFiltered indicates an expected call of ListStaffFiltered.
func (mr *MockStaffRepositoryMockRecorder) ListStaffFiltered(ctx, merchantID, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStaffFiltered", reflect.TypeOf((*MockStaffRepository)(nil).ListStaffFiltered), ctx, merchantID, nameContains)
}

// MockMerchantRepository is a mock of MerchantRepository interface.
type MockMerchantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryMockRecorder
}

// MockMerchantRepositoryMockRecorder is the mock recorder for MockMerchantRepository.
type MockMerchantRepositoryMockRecorder struct {
	mock *MockMerchantRepository
}

// NewMockMerchantRepository creates a new mock instance.
func NewMockMerchantRepository(ctrl *gomock.Controller) *MockMerchantRepository {
	mock := &MockMerchantRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepository) EXPECT() *MockMerchantRepositoryMockRecorder {
	return m.recorder
}

// CreateMerchant mocks base method.
func (m *MockMerchantRepository) CreateMerchant(ctx context.Context, merchant *models.Merchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMerchant", ctx, merchant)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockMerchantRepositoryMockRecorder) CreateMerchant(ctx, merchant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockMerchantRepository)(nil).CreateMerchant), ctx, merchant)
}

// DeleteMerchant mocks base method.
func (m *MockMerchantRepository) DeleteMerchant(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMerchant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMerchant indicates an expected call of DeleteMerchant.
func (mr *MockMerchantRepositoryMockRecorder) DeleteMerchant(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMerchant", reflect.TypeOf((*MockMerchantRepository)(nil).DeleteMerchant), ctx, id)
}

// GetMerchantByID mocks base method.
func (m *MockMerchantRepository) GetMerchantByID(ctx context.Context, id string) (*models.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(*models.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockMerchantRepositoryMockRecorder) GetMerchantByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockMerchantRepository)(nil).GetMerchantByID), ctx, id)
}

// ListMerchantsFiltered mocks base method.
func (m *MockMerchantRepository) ListMerchantsFiltered(ctx context.Context, nameContains string) ([]models.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMerchantsFiltered", ctx, nameContains)
	ret0, _ := ret[0].([]models.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMerchantsFiltered indicates an expected call of ListMerchantsFiltered.
func (mr *MockMerchantRepositoryMockRecorder) ListMerchantsFiltered(ctx, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMerchantsFiltered", reflect.TypeOf((*MockMerchantRepository)(nil).ListMerchantsFiltered), ctx, nameContains)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockRepository) CreateBooking(ctx context.Context, booking *models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockRepository)(nil).CreateBooking), ctx, booking)
}

// CreateMerchant mocks base method.
func (m *MockRepository) CreateMerchant(ctx context.Context, merchant *models.Merchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMerchant", ctx, merchant)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockRepositoryMockRecorder) CreateMerchant(ctx, merchant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockRepository)(nil).CreateMerchant), ctx, merchant)
}

// CreateService mocks base method.
func (m *MockRepository) CreateService(ctx context.Context, service *models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateService indicates an expected call of CreateService.
func (mr *MockRepositoryMockRecorder) CreateService(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockRepository)(nil).CreateService), ctx, service)
}

// CreateStaff mocks base method.
func (m *MockRepository) CreateStaff(ctx context.Context, staff *models.Staff) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaff", ctx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStaff indicates an expected call of CreateStaff.
func (mr *MockRepositoryMockRecorder) CreateStaff(ctx, staff interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaff", reflect.TypeOf((*MockRepository)(nil).CreateStaff), ctx, staff)
}

// DeleteMerchant mocks base method.
func (m *MockRepository) DeleteMerchant(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMerchant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMerchant indicates an expected call of DeleteMerchant.
func (mr *MockRepositoryMockRecorder) DeleteMerchant(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMerchant", reflect.TypeOf((*MockRepository)(nil).DeleteMerchant), ctx, id)
}

// DeleteService mocks base method.
func (m *MockRepository) DeleteService(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteService", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockRepositoryMockRecorder) DeleteService(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockRepository)(nil).DeleteService), ctx, id)
}

// DeleteStaff mocks base method.
func (m *MockRepository) DeleteStaff(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStaff", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStaff indicates an expected call of DeleteStaff.
func (mr *MockRepositoryMockRecorder) DeleteStaff(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStaff", reflect.TypeOf((*MockRepository)(nil).DeleteStaff), ctx, id)
}

// GetBookingByID mocks base method.
func (m *MockRepository) GetBookingByID(ctx context.Context, id string) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, id)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockRepositoryMockRecorder) GetBookingByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockRepository)(nil).GetBookingByID), ctx, id)
}

// GetBookingsByServiceAndDate mocks base method.
func (m *MockRepository) GetBookingsByServiceAndDate(ctx context.Context, serviceID string, date time.Time) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByServiceAndDate", ctx, serviceID, date)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByServiceAndDate indicates an expected call of GetBookingsByServiceAndDate.
func (mr *MockRepositoryMockRecorder) GetBookingsByServiceAndDate(ctx, serviceID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByServiceAndDate", reflect.TypeOf((*MockRepository)(nil).GetBookingsByServiceAndDate), ctx, serviceID, date)
}

// GetBookingsByUserID mocks base method.
func (m *MockRepository) GetBookingsByUserID(ctx context.Context, userID, status string, limit, offset int) ([]models.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockRepositoryMockRecorder) GetBookingsByUserID(ctx, userID, status, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockRepository)(nil).GetBookingsByUserID), ctx, userID, status, limit, offset)
}

// GetMerchantByID mocks base method.
func (m *MockRepository) GetMerchantByID(ctx context.Context, id string) (*models.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(*models.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockRepositoryMockRecorder) GetMerchantByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockRepository)(nil).GetMerchantByID), ctx, id)
}

// GetServiceByID mocks base method.
func (m *MockRepository) GetServiceByID(ctx context.Context, id string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByID", ctx, id)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByID indicates an expected call of GetServiceByID.
func (mr *MockRepositoryMockRecorder) GetServiceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByID", reflect.TypeOf((*MockRepository)(nil).GetServiceByID), ctx, id)
}

// GetServicesByMerchantID mocks base method.
func (m *MockRepository) GetServicesByMerchantID(ctx context.Context, merchantID string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicesByMerchantID indicates an expected call of GetServicesByMerchantID.
func (mr *MockRepositoryMockRecorder) GetServicesByMerchantID(ctx, merchantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesByMerchantID", reflect.TypeOf((*MockRepository)(nil).GetServicesByMerchantID), ctx, merchantID)
}

// GetStaffByID mocks base method.
func (m *MockRepository) GetStaffByID(ctx context.Context, id string) (*models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffByID", ctx, id)
	ret0, _ := ret[0].(*models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffByID indicates an expected call of GetStaffByID.
func (mr *MockRepositoryMockRecorder) GetStaffByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffByID", reflect.TypeOf((*MockRepository)(nil).GetStaffByID), ctx, id)
}

// GetStaffByMerchantID mocks base method.
func (m *MockRepository) GetStaffByMerchantID(ctx context.Context, merchantID string) ([]models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffByMerchantID indicates an expected call of GetStaffByMerchantID.
func (mr *MockRepositoryMockRecorder) GetStaffByMerchantID(ctx, merchantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffByMerchantID", reflect.TypeOf((*MockRepository)(nil).GetStaffByMerchantID), ctx, merchantID)
}

// ListMerchantsFiltered mocks base method.
func (m *MockRepository) ListMerchantsFiltered(ctx context.Context, nameContains string) ([]models.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMerchantsFiltered", ctx, nameContains)
	ret0, _ := ret[0].([]models.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMerchantsFiltered indicates an expected call of ListMerchantsFiltered.
func (mr *MockRepositoryMockRecorder) ListMerchantsFiltered(ctx, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMerchantsFiltered", reflect.TypeOf((*MockRepository)(nil).ListMerchantsFiltered), ctx, nameContains)
}

// ListServicesFiltered mocks base method.
func (m *MockRepository) ListServicesFiltered(ctx context.Context, merchantID, nameContains string) ([]models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesFiltered", ctx, merchantID, nameContains)
	ret0, _ := ret[0].([]models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesFiltered indicates an expected call of ListServicesFiltered.
func (mr *MockRepositoryMockRecorder) ListServicesFiltered(ctx, merchantID, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesFiltered", reflect.TypeOf((*MockRepository)(nil).ListServicesFiltered), ctx, merchantID, nameContains)
}

// ListStaffFiltered mocks base method.
func (m *MockRepository) ListStaffFiltered(ctx context.Context, merchantID, nameContains string) ([]models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStaffFiltered", ctx, merchantID, nameContains)
	ret0, _ := ret[0].([]models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStaffFiltered indicates an expected call of ListStaffFiltered.
func (mr *MockRepositoryMockRecorder) ListStaffFiltered(ctx, merchantID, nameContains interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStaffFiltered", reflect.TypeOf((*MockRepository)(nil).ListStaffFiltered), ctx, merchantID, nameContains)
}

// UpdateBookingStatus mocks base method.
func (m *MockRepository) UpdateBookingStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockRepositoryMockRecorder) UpdateBookingStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockRepository)(nil).UpdateBookingStatus), ctx, id, status)
}
