// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/booking_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "bookerbotapi/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockBookingRepository) CreateBooking(ctx context.Context, booking *models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingRepository)(nil).CreateBooking), ctx, booking)
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(ctx context.Context, id string) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", ctx, id)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), ctx, id)
}

// GetBookingsByServiceAndDate mocks base method.
func (m *MockBookingRepository) GetBookingsByServiceAndDate(ctx context.Context, serviceID string, date time.Time) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByServiceAndDate", ctx, serviceID, date)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByServiceAndDate indicates an expected call of GetBookingsByServiceAndDate.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByServiceAndDate(ctx, serviceID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByServiceAndDate", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByServiceAndDate), ctx, serviceID, date)
}

// GetBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetBookingsByUserID(ctx context.Context, userID, status string, limit, offset int) ([]models.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByUserID(ctx, userID, status, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByUserID), ctx, userID, status, limit, offset)
}

// GetMerchantByID mocks base method.
func (m *MockBookingRepository) GetMerchantByID(ctx context.Context, id string) (*models.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(*models.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockBookingRepositoryMockRecorder) GetMerchantByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockBookingRepository)(nil).GetMerchantByID), ctx, id)
}

// GetServiceByID mocks base method.
func (m *MockBookingRepository) GetServiceByID(ctx context.Context, id string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByID", ctx, id)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceByID indicates an expected call of GetServiceByID.
func (mr *MockBookingRepositoryMockRecorder) GetServiceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByID", reflect.TypeOf((*MockBookingRepository)(nil).GetServiceByID), ctx, id)
}

// GetStaffByID mocks base method.
func (m *MockBookingRepository) GetStaffByID(ctx context.Context, id string) (*models.Staff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffByID", ctx, id)
	ret0, _ := ret[0].(*models.Staff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffByID indicates an expected call of GetStaffByID.
func (mr *MockBookingRepositoryMockRecorder) GetStaffByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffByID", reflect.TypeOf((*MockBookingRepository)(nil).GetStaffByID), ctx, id)
}

// UpdateBookingStatus mocks base method.
func (m *MockBookingRepository) UpdateBookingStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookingStatus indicates an expected call of UpdateBookingStatus.
func (mr *MockBookingRepositoryMockRecorder) UpdateBookingStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookingStatus", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBookingStatus), ctx, id, status)
}
