// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.17.0-bufbuild-protocompile-easyp
// source: user/v1/user.proto

// Package содержит API v1 для работы с сервисом BotBooker

package user_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Перечисление для указания пола пользователя
type Gender int32

const (
	// Пол не указан
	Gender_GENDER_UNSPECIFIED Gender = 0
	// Мужской пол
	Gender_GENDER_MALE Gender = 1
	// Женский пол
	Gender_GENDER_FEMALE Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// Модель пользователя
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор пользователя (UUIDv4)
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Электронная почта
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Имя пользователя
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Фамилия пользователя
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Отчество пользователя (при наличии)
	MiddleName string `protobuf:"bytes,5,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// Номер телефона в международном формате
	PhoneNumber string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пол пользователя
	Gender Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=user.v1.Gender" json:"gender,omitempty"`
	// Дата рождения пользователя
	BirthDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	// Время создания профиля
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Время последнего обновления профиля
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *User) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Запрос на создание пользователя
type UserServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email обязателен к заполнению и должен быть валидным адресом
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Имя должно быть от 1 до 100 символов
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Фамилия должна быть от 1 до 100 символов
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Отчество (опционально, до 100 символов)
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// Номер телефона в формате E.164 (например, +79991234567)
	PhoneNumber string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Пол пользователя (по умолчанию UNSPECIFIED, если не передан)
	Gender Gender `protobuf:"varint,6,opt,name=gender,proto3,enum=user.v1.Gender" json:"gender,omitempty"`
	// Дата рождения пользователя
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceCreateRequest) Reset() {
	*x = UserServiceCreateRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceCreateRequest) ProtoMessage() {}

func (x *UserServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*UserServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserServiceCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserServiceCreateRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserServiceCreateRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserServiceCreateRequest) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *UserServiceCreateRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserServiceCreateRequest) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UserServiceCreateRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

// Ответ с данными созданного пользователя
type UserServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Созданный пользователь
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceCreateResponse) Reset() {
	*x = UserServiceCreateResponse{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceCreateResponse) ProtoMessage() {}

func (x *UserServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*UserServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserServiceCreateResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Запрос на получение пользователя
type UserServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID пользователя обязателен и должен быть валидным UUID
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceGetRequest) Reset() {
	*x = UserServiceGetRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceGetRequest) ProtoMessage() {}

func (x *UserServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceGetRequest.ProtoReflect.Descriptor instead.
func (*UserServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserServiceGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Ответ с данными запрошенного пользователя
type UserServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Найденный пользователь
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceGetResponse) Reset() {
	*x = UserServiceGetResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceGetResponse) ProtoMessage() {}

func (x *UserServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceGetResponse.ProtoReflect.Descriptor instead.
func (*UserServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserServiceGetResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Запрос на обновление пользователя
type UserServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID обновляемого пользователя
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Поля обернуты в wrappers для поддержки частичного обновления (PATCH)
	FirstName   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName  *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	PhoneNumber *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Ссылка на обертку для Enum, чтобы отличать "не передано" от "значение 0"
	Gender *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	// Новая дата рождения
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceUpdateRequest) Reset() {
	*x = UserServiceUpdateRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceUpdateRequest) ProtoMessage() {}

func (x *UserServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserServiceUpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserServiceUpdateRequest) GetFirstName() *wrapperspb.StringValue {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *UserServiceUpdateRequest) GetLastName() *wrapperspb.StringValue {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *UserServiceUpdateRequest) GetMiddleName() *wrapperspb.StringValue {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

func (x *UserServiceUpdateRequest) GetPhoneNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *UserServiceUpdateRequest) GetGender() *wrapperspb.Int32Value {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *UserServiceUpdateRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

// Ответ с обновленными данными пользователя
type UserServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Обновленный пользователь
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceUpdateResponse) Reset() {
	*x = UserServiceUpdateResponse{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceUpdateResponse) ProtoMessage() {}

func (x *UserServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserServiceUpdateResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Запрос на удаление пользователя
type UserServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID удаляемого пользователя
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceDeleteRequest) Reset() {
	*x = UserServiceDeleteRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceDeleteRequest) ProtoMessage() {}

func (x *UserServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserServiceDeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\"\x8a\x03\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x05 \x01(\tR\n" +
	"middleName\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12'\n" +
	"\x06gender\x18\a \x01(\x0e2\x0f.user.v1.GenderR\x06gender\x129\n" +
	"\n" +
	"birth_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x02\n" +
	"\x18UserServiceCreateRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12(\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\tfirstName\x12&\n" +
	"\tlast_name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\blastName\x12(\n" +
	"\vmiddle_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x18dR\n" +
	"middleName\x12;\n" +
	"\fphone_number\x18\x05 \x01(\tB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\vphoneNumber\x12'\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x0f.user.v1.GenderR\x06gender\x129\n" +
	"\n" +
	"birth_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\">\n" +
	"\x19UserServiceCreateResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"5\n" +
	"\x15UserServiceGetRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\";\n" +
	"\x16UserServiceGetResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\xd9\x03\n" +
	"\x18UserServiceUpdateRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x12F\n" +
	"\n" +
	"first_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\t\xfaB\x06r\x04\x10\x01\x18dR\tfirstName\x12D\n" +
	"\tlast_name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\t\xfaB\x06r\x04\x10\x01\x18dR\blastName\x12F\n" +
	"\vmiddle_name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\a\xfaB\x04r\x02\x18dR\n" +
	"middleName\x12Y\n" +
	"\fphone_number\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xfaB\x15r\x132\x11^\\+[1-9]\\d{1,14}$R\vphoneNumber\x123\n" +
	"\x06gender\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06gender\x129\n" +
	"\n" +
	"birth_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\">\n" +
	"\x19UserServiceUpdateResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"8\n" +
	"\x18UserServiceDeleteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x022\xa3\x03\n" +
	"\vUserService\x12e\n" +
	"\x06Create\x12!.user.v1.UserServiceCreateRequest\x1a\".user.v1.UserServiceCreateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12`\n" +
	"\x03Get\x12\x1e.user.v1.UserServiceGetRequest\x1a\x1f.user.v1.UserServiceGetResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/{uuid}\x12l\n" +
	"\x06Update\x12!.user.v1.UserServiceUpdateRequest\x1a\".user.v1.UserServiceUpdateResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/users/{uuid}\x12]\n" +
	"\x06Delete\x12!.user.v1.UserServiceDeleteRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/users/{uuid}B8Z6github.com/botbooker/bb-core/pkg/proto/user/v1;user_v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_v1_user_proto_goTypes = []any{
	(Gender)(0),                       // 0: user.v1.Gender
	(*User)(nil),                      // 1: user.v1.User
	(*UserServiceCreateRequest)(nil),  // 2: user.v1.UserServiceCreateRequest
	(*UserServiceCreateResponse)(nil), // 3: user.v1.UserServiceCreateResponse
	(*UserServiceGetRequest)(nil),     // 4: user.v1.UserServiceGetRequest
	(*UserServiceGetResponse)(nil),    // 5: user.v1.UserServiceGetResponse
	(*UserServiceUpdateRequest)(nil),  // 6: user.v1.UserServiceUpdateRequest
	(*UserServiceUpdateResponse)(nil), // 7: user.v1.UserServiceUpdateResponse
	(*UserServiceDeleteRequest)(nil),  // 8: user.v1.UserServiceDeleteRequest
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),    // 10: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),     // 11: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
}
var file_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.User.gender:type_name -> user.v1.Gender
	9,  // 1: user.v1.User.birth_date:type_name -> google.protobuf.Timestamp
	9,  // 2: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: user.v1.UserServiceCreateRequest.gender:type_name -> user.v1.Gender
	9,  // 5: user.v1.UserServiceCreateRequest.birth_date:type_name -> google.protobuf.Timestamp
	1,  // 6: user.v1.UserServiceCreateResponse.user:type_name -> user.v1.User
	1,  // 7: user.v1.UserServiceGetResponse.user:type_name -> user.v1.User
	10, // 8: user.v1.UserServiceUpdateRequest.first_name:type_name -> google.protobuf.StringValue
	10, // 9: user.v1.UserServiceUpdateRequest.last_name:type_name -> google.protobuf.StringValue
	10, // 10: user.v1.UserServiceUpdateRequest.middle_name:type_name -> google.protobuf.StringValue
	10, // 11: user.v1.UserServiceUpdateRequest.phone_number:type_name -> google.protobuf.StringValue
	11, // 12: user.v1.UserServiceUpdateRequest.gender:type_name -> google.protobuf.Int32Value
	9,  // 13: user.v1.UserServiceUpdateRequest.birth_date:type_name -> google.protobuf.Timestamp
	1,  // 14: user.v1.UserServiceUpdateResponse.user:type_name -> user.v1.User
	2,  // 15: user.v1.UserService.Create:input_type -> user.v1.UserServiceCreateRequest
	4,  // 16: user.v1.UserService.Get:input_type -> user.v1.UserServiceGetRequest
	6,  // 17: user.v1.UserService.Update:input_type -> user.v1.UserServiceUpdateRequest
	8,  // 18: user.v1.UserService.Delete:input_type -> user.v1.UserServiceDeleteRequest
	3,  // 19: user.v1.UserService.Create:output_type -> user.v1.UserServiceCreateResponse
	5,  // 20: user.v1.UserService.Get:output_type -> user.v1.UserServiceGetResponse
	7,  // 21: user.v1.UserService.Update:output_type -> user.v1.UserServiceUpdateResponse
	12, // 22: user.v1.UserService.Delete:output_type -> google.protobuf.Empty
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
