// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user/v1/user.proto

package user_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _user_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on User with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *User) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on User with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UserMultiError, or nil if none found.
func (m *User) ValidateAll() error {
	return m.validate(true)
}

func (m *User) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	// no validation rules for Email

	// no validation rules for FirstName

	// no validation rules for LastName

	// no validation rules for MiddleName

	// no validation rules for PhoneNumber

	// no validation rules for Gender

	if all {
		switch v := interface{}(m.GetBirthDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBirthDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserValidationError{
				field:  "BirthDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserMultiError(errors)
	}

	return nil
}

// UserMultiError is an error wrapping multiple validation errors returned by
// User.ValidateAll() if the designated constraints aren't met.
type UserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMultiError) AllErrors() []error { return m }

// UserValidationError is the validation error returned by User.Validate if the
// designated constraints aren't met.
type UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserValidationError) ErrorName() string { return "UserValidationError" }

// Error satisfies the builtin error interface
func (e UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserValidationError{}

// Validate checks the field values on UserServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceCreateRequestMultiError, or nil if none found.
func (m *UserServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = UserServiceCreateRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetFirstName()); l < 1 || l > 100 {
		err := UserServiceCreateRequestValidationError{
			field:  "FirstName",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetLastName()); l < 1 || l > 100 {
		err := UserServiceCreateRequestValidationError{
			field:  "LastName",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMiddleName()) > 100 {
		err := UserServiceCreateRequestValidationError{
			field:  "MiddleName",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UserServiceCreateRequest_PhoneNumber_Pattern.MatchString(m.GetPhoneNumber()) {
		err := UserServiceCreateRequestValidationError{
			field:  "PhoneNumber",
			reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Gender

	if all {
		switch v := interface{}(m.GetBirthDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceCreateRequestValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceCreateRequestValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBirthDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceCreateRequestValidationError{
				field:  "BirthDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServiceCreateRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceCreateRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *UserServiceCreateRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// UserServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by UserServiceCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type UserServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceCreateRequestMultiError) AllErrors() []error { return m }

// UserServiceCreateRequestValidationError is the validation error returned by
// UserServiceCreateRequest.Validate if the designated constraints aren't met.
type UserServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceCreateRequestValidationError) ErrorName() string {
	return "UserServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceCreateRequestValidationError{}

var _UserServiceCreateRequest_PhoneNumber_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on UserServiceCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceCreateResponseMultiError, or nil if none found.
func (m *UserServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceCreateResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceCreateResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceCreateResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServiceCreateResponseMultiError(errors)
	}

	return nil
}

// UserServiceCreateResponseMultiError is an error wrapping multiple validation
// errors returned by UserServiceCreateResponse.ValidateAll() if the
// designated constraints aren't met.
type UserServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceCreateResponseMultiError) AllErrors() []error { return m }

// UserServiceCreateResponseValidationError is the validation error returned by
// UserServiceCreateResponse.Validate if the designated constraints aren't met.
type UserServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceCreateResponseValidationError) ErrorName() string {
	return "UserServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceCreateResponseValidationError{}

// Validate checks the field values on UserServiceGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceGetRequestMultiError, or nil if none found.
func (m *UserServiceGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = UserServiceGetRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserServiceGetRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceGetRequest) _validateUuid(uuid string) error {
	if matched := _user_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserServiceGetRequestMultiError is an error wrapping multiple validation
// errors returned by UserServiceGetRequest.ValidateAll() if the designated
// constraints aren't met.
type UserServiceGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceGetRequestMultiError) AllErrors() []error { return m }

// UserServiceGetRequestValidationError is the validation error returned by
// UserServiceGetRequest.Validate if the designated constraints aren't met.
type UserServiceGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceGetRequestValidationError) ErrorName() string {
	return "UserServiceGetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceGetRequestValidationError{}

// Validate checks the field values on UserServiceGetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceGetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceGetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceGetResponseMultiError, or nil if none found.
func (m *UserServiceGetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceGetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceGetResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceGetResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceGetResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServiceGetResponseMultiError(errors)
	}

	return nil
}

// UserServiceGetResponseMultiError is an error wrapping multiple validation
// errors returned by UserServiceGetResponse.ValidateAll() if the designated
// constraints aren't met.
type UserServiceGetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceGetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceGetResponseMultiError) AllErrors() []error { return m }

// UserServiceGetResponseValidationError is the validation error returned by
// UserServiceGetResponse.Validate if the designated constraints aren't met.
type UserServiceGetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceGetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceGetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceGetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceGetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceGetResponseValidationError) ErrorName() string {
	return "UserServiceGetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceGetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceGetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceGetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceGetResponseValidationError{}

// Validate checks the field values on UserServiceUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceUpdateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceUpdateRequestMultiError, or nil if none found.
func (m *UserServiceUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = UserServiceUpdateRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if wrapper := m.GetFirstName(); wrapper != nil {

		if l := utf8.RuneCountInString(wrapper.GetValue()); l < 1 || l > 100 {
			err := UserServiceUpdateRequestValidationError{
				field:  "FirstName",
				reason: "value length must be between 1 and 100 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if wrapper := m.GetLastName(); wrapper != nil {

		if l := utf8.RuneCountInString(wrapper.GetValue()); l < 1 || l > 100 {
			err := UserServiceUpdateRequestValidationError{
				field:  "LastName",
				reason: "value length must be between 1 and 100 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if wrapper := m.GetMiddleName(); wrapper != nil {

		if utf8.RuneCountInString(wrapper.GetValue()) > 100 {
			err := UserServiceUpdateRequestValidationError{
				field:  "MiddleName",
				reason: "value length must be at most 100 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if wrapper := m.GetPhoneNumber(); wrapper != nil {

		if !_UserServiceUpdateRequest_PhoneNumber_Pattern.MatchString(wrapper.GetValue()) {
			err := UserServiceUpdateRequestValidationError{
				field:  "PhoneNumber",
				reason: "value does not match regex pattern \"^\\\\+[1-9]\\\\d{1,14}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if all {
		switch v := interface{}(m.GetGender()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceUpdateRequestValidationError{
					field:  "Gender",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceUpdateRequestValidationError{
					field:  "Gender",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGender()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceUpdateRequestValidationError{
				field:  "Gender",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetBirthDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceUpdateRequestValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceUpdateRequestValidationError{
					field:  "BirthDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBirthDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceUpdateRequestValidationError{
				field:  "BirthDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServiceUpdateRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceUpdateRequest) _validateUuid(uuid string) error {
	if matched := _user_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserServiceUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by UserServiceUpdateRequest.ValidateAll() if the designated
// constraints aren't met.
type UserServiceUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceUpdateRequestMultiError) AllErrors() []error { return m }

// UserServiceUpdateRequestValidationError is the validation error returned by
// UserServiceUpdateRequest.Validate if the designated constraints aren't met.
type UserServiceUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceUpdateRequestValidationError) ErrorName() string {
	return "UserServiceUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceUpdateRequestValidationError{}

var _UserServiceUpdateRequest_PhoneNumber_Pattern = regexp.MustCompile("^\\+[1-9]\\d{1,14}$")

// Validate checks the field values on UserServiceUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceUpdateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceUpdateResponseMultiError, or nil if none found.
func (m *UserServiceUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserServiceUpdateResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserServiceUpdateResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserServiceUpdateResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserServiceUpdateResponseMultiError(errors)
	}

	return nil
}

// UserServiceUpdateResponseMultiError is an error wrapping multiple validation
// errors returned by UserServiceUpdateResponse.ValidateAll() if the
// designated constraints aren't met.
type UserServiceUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceUpdateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceUpdateResponseMultiError) AllErrors() []error { return m }

// UserServiceUpdateResponseValidationError is the validation error returned by
// UserServiceUpdateResponse.Validate if the designated constraints aren't met.
type UserServiceUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceUpdateResponseValidationError) ErrorName() string {
	return "UserServiceUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceUpdateResponseValidationError{}

// Validate checks the field values on UserServiceDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceDeleteRequestMultiError, or nil if none found.
func (m *UserServiceDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = UserServiceDeleteRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserServiceDeleteRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceDeleteRequest) _validateUuid(uuid string) error {
	if matched := _user_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserServiceDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by UserServiceDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type UserServiceDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceDeleteRequestMultiError) AllErrors() []error { return m }

// UserServiceDeleteRequestValidationError is the validation error returned by
// UserServiceDeleteRequest.Validate if the designated constraints aren't met.
type UserServiceDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceDeleteRequestValidationError) ErrorName() string {
	return "UserServiceDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceDeleteRequestValidationError{}
