// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/availability/manager.go

// Package mock_availability is a generated GoMock package.
package mock_availability

import (
	models "bookerbotapi/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockAManager is a mock of AManager interface.
type MockAManager struct {
	ctrl     *gomock.Controller
	recorder *MockAManagerMockRecorder
}

// MockAManagerMockRecorder is the mock recorder for MockAManager.
type MockAManagerMockRecorder struct {
	mock *MockAManager
}

// NewMockAManager creates a new mock instance.
func NewMockAManager(ctrl *gomock.Controller) *MockAManager {
	mock := &MockAManager{ctrl: ctrl}
	mock.recorder = &MockAManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAManager) EXPECT() *MockAManagerMockRecorder {
	return m.recorder
}

// CheckAvailability mocks base method.
func (m *MockAManager) CheckAvailability(ctx context.Context, service *models.Service, startTime time.Time, durationMinutes int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", ctx, service, startTime, durationMinutes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockAManagerMockRecorder) CheckAvailability(ctx, service, startTime, durationMinutes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockAManager)(nil).CheckAvailability), ctx, service, startTime, durationMinutes)
}

// GetOrCreateBitmap mocks base method.
func (m *MockAManager) GetOrCreateBitmap(ctx context.Context, service *models.Service, date time.Time) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateBitmap", ctx, service, date)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateBitmap indicates an expected call of GetOrCreateBitmap.
func (mr *MockAManagerMockRecorder) GetOrCreateBitmap(ctx, service, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateBitmap", reflect.TypeOf((*MockAManager)(nil).GetOrCreateBitmap), ctx, service, date)
}

// ReserveBooking mocks base method.
func (m *MockAManager) ReserveBooking(ctx context.Context, service *models.Service, startTime time.Time, durationMinutes int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveBooking", ctx, service, startTime, durationMinutes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveBooking indicates an expected call of ReserveBooking.
func (mr *MockAManagerMockRecorder) ReserveBooking(ctx, service, startTime, durationMinutes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveBooking", reflect.TypeOf((*MockAManager)(nil).ReserveBooking), ctx, service, startTime, durationMinutes)
}
